# Generated by Django 4.2 on 2023-05-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerid', models.CharField(default='', max_length=40, primary_key=True, serialize=False)),
                ('index', models.IntegerField(default=0, unique=True)),
                ('firstname', models.TextField(default='')),
                ('lastname', models.TextField(default='')),
                ('company', models.CharField(default='', max_length=40)),
                ('city', models.CharField(default='', max_length=40)),
                ('country', models.CharField(default='', max_length=100)),
                ('phone1', models.CharField(default='', max_length=50)),
                ('phone2', models.CharField(default='', max_length=50)),
                ('email', models.TextField(default='')),
                ('subscriptiondate', models.DateField(default='')),
                ('website', models.CharField(default='', max_length=100)),
                ('filename_index', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
