# Generated by Django 4.2 on 2023-04-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(default='', max_length=40)),
                ('firstname', models.TextField(default='')),
                ('lastname', models.TextField(default='')),
                ('company', models.CharField(default='', max_length=40)),
                ('city', models.CharField(default='', max_length=40)),
                ('country', models.CharField(default='', max_length=100)),
                ('phone1', models.CharField(default='', max_length=50)),
                ('phone2', models.CharField(default='', max_length=50)),
                ('email', models.TextField(default='')),
                ('subscriptiondate', models.DateField(default='')),
                ('website', models.CharField(default='', max_length=100)),
                ('cleanedphone1', models.CharField(default='', max_length=50)),
                ('cleanedphone2', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
